steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/test-bench-sofia-villalobos/sbvillalobosm/sofia-villalobos:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/test-bench-sofia-villalobos/sbvillalobosm/sofia-villalobos:$SHORT_SHA']
